rails/config/routes.rb
Rails.application.routes.draw do
  resources :locations

  get 'home/index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/location.rb
class Location < ApplicationRecord
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     @locations = Location.all
  end
end

rails/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def edit
    @location = Location.find(params[:id])
  end

  def destroy
    raise foo
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_path
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to @location
    else
      render 'new'
    end
  end

  def update
    @location = Location.find(params[:id])

    if @location.update(location_params)
      redirect_to @location
    else
      render 'edit'
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  private
  def location_params
    params.require(:location).permit(:title, :latitude, :longitude, :description, :status)
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/home_helper.rb
module HomeHelper
end

rails/app/helpers/homes_helper.rb
module HomesHelper
end

rails/app/helpers/locations_helper.rb
module LocationsHelper
end

rails/app/views/home/index.html.erb
  <style type="text/css" media="screen">
       div, body {
          font-family: "Lucida Grande", "Bitstream Vera Sans", "Verdana";
       }

        body {
          text-align:center;
          margin: 0;
          padding: 0;
          background-color: #ffffff;
          font-size: 13px;
          color: #333;
        }

      .vcenter {
         display: inline;
         top: 50%;
         transform: translateY(-50%);
         -webkit-transform: translateY(-50%);
      }

        h1 {
          font-size: 28px;
          color: #333;
        }

  </style>

  <div id="map" style="margin:0 auto;width:800px;height:800px;background:yellow"></div>

  <div style="position: absolute; left: 0; bottom: 0; z-index: 9999; width: 100%">
    <div style="margin: 0 auto; text-align: center;">
      <p><%= image_tag("stopoaching_burned.png", size: '100x90') %></p>
      <div class="vcenter" style="font-size: 36px; color: #e1e1e1;">Poach Stopper</div>
    </div>
  </div>

<script>

  window.locations = <%=raw @locations.to_json %>;
  if(window.locations.length < 2) {
    console.log("refreshing");

    setTimeout(function() {
      window.location.reload();
    }, 5000);
  }

  function initMap() {
    var height = window.innerHeight;
    var width = document.body.clientWidth;
    var mapDiv = document.getElementById("map")

    mapDiv.style.width = width + "px"
    mapDiv.style.height = height + "px"

    var map = new google.maps.Map(mapDiv, {
      zoom: 8,
      center: {lat: 41.3, lng: -68.5},
      mapTypeId: 'satellite'
    });

    var georgesLayer = new google.maps.KmlLayer({
      url: 'http://poachstopper.net/georges2.kml',
      preserveViewport: true,
      suppressInfoWindows: true,
      pane: "floatPane"
    });
    georgesLayer.setMap(map);

    locations.map(function(loc) {
      var anima = null;
      var icon = null;
      var image2 = 'http://poachstopper.net/images/danger-icon-tiny.png';

      if (loc['status'] !== 'OK') {
        anima = google.maps.Animation.BOUNCE;
        icon = image2;
      }

      var marker = new google.maps.Marker({
        position: {lat: loc['latitude'], lng: loc['longitude']},
        animation: anima,
        map: map, title: loc['title'],
        icon: icon
      });
      marker.addListener('click', toggleBounce);
    });
}

  function toggleBounce() {
    var marker_title = this.title;

    if (this.getAnimation() !== null) {
      this.setAnimation(null);
      this.setIcon(null);
    }

    var this_location = locations.filter(function(d) { return d.title == marker_title });
    var info_content = "<h3>" + this_location[0].title + "</h3><p>" + this_location[0].description + "</p>";
    info_content += "<ul><li>Lat: "+this_location[0].latitude+"</li><li>Lon: "+this_location[0].longitude+"</li></ul>";
    var infowindow = new google.maps.InfoWindow({
      content: info_content
    });
    infowindow.open(map, this);
  }
</script>
<script async defer
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAKT9_DACKx2g8Kbxqe6C9Tpzy5PyrogWU&callback=initMap">
</script>

</body>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoachStopper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails/app/views/locations/edit.html.erb
<%= javascript_include_tag 'application' %>

<h1>Edit Location</h1>

<%= form_for :location, url: location_path(@location), method: :patch do |f|  %>
<p>
  Title: <%= f.text_field :title %>
</p>

<p>
  Latitude: <%= f.text_field :latitude %><br>
  Longitude <%= f.text_field :longitude %>
</p>

<p>
  Description<br><%= f.text_area :description, size: "60x10"  %>
</p>

<p>
  Status: <%= f.text_field :status %>
</p>

<p>
  <%= submit_tag "Change Location" %>
</p>
<% end %>

<%= link_to 'Really Delete This Location', location_path(@location), data: { confirm: 'Are you sure?' }, method: :delete %>

rails/app/views/locations/index.html.erb
<h1>All Locations</h1>

<table>
  <tr>
    <th>&nbsp;</th>
    <th>Title</th>
    <th>Lat/Long</th>
    <th>Description</th>
    <th>Status</th>
    <th>ID</th>
  </tr>

  <% @locations.each do |location| %>
  <tr>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= location.title %></td>
    <td><%= location.latitude %>/<%= location.longitude %></td>
    <td><%= location.description %></td>
    <td><%= location.status %></td>
    <td><%= location.id %></td>
  </tr>
  <% end %>
  </table>

rails/app/views/locations/new.html.erb
<h1>Enter a New Location</h1>

<%= form_for :location, url: locations_path(@location) do |f|  %>
<p>
  Title: <%= f.text_field :title %>
</p>

<p>
  Latitude: <%= f.text_field :latitude %><br>
  Longitude <%= f.text_field :longitude %>
</p>

<p>
  Description<br><%= f.text_area :description, size: "60x10"  %>
</p>

<p>
  Status: <%= f.text_field :status %>
</p>

<p>
  <%= submit_tag "Add Location" %>
</p>
<% end %>

rails/app/views/locations/show.html.erb
<p>
  Title: <%= @location.title %>
</p>
<p>
  Latitude: <%= @location.latitude %><br>
  Longitude <%= @location.longitude %>
</p>

<p>
  Description<br><%= @location.description %>
</p>

<p>
  Status: <%= @location.status %>
</p>

<p>
  ID: <%= @location.id %>
</p>

<%= link_to 'Edit This Location', edit_location_path(@location) %>